### ISSUE TITLE
`reahl build` fails on Cygwin

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#143]
The class LocalAptRepository makes [calls](https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L487) to something called `apt-ftparchive` which does not exist on Cygwin. 

How can I get `reahl build` working on Cygwin?

**Comment by IwanVosloo** [comment]
Good one, thanks. We have that installed on ubuntu (which is where we develop) so never realised it gets called in other contexts.

apt-ftparchive is part of apt-utils on debian-based distros. Can you perhaps install that on cygwyn?

You are also going to need gpg.

If you can't install these, a workaround is perhaps to create an executable script in your path with the name "apt-ftparchive" which does nothing but return successfully.  Since you do not distribute .debs you can safely stub out what this is trying to do (which is to maintain a local archive of .debs).

**Comment by IwanVosloo** [comment]
We'll have to think about how to handle this. We always maintain a "local" apt repository. But most won't use such a thing, so this is unnecessary. Perhaps we should just issue a warning when this command runs and does not find the necessary commandline tools.

**Comment by metaperl** [comment]
I could not find `apt-ftparchive` in Cygwin - https://cygwin.com/cgi-bin2/package-grep.cgi?grep=apt-ftparchive&arch=x86_64

yes, feel free to put some thought into how to handle this.

**Comment by IwanVosloo** [comment]
TODO: emit a warning when apt-ftparchive is not installed:

"Cannot do housekeeping of the local apt archive, apt-ftparchive not found in your path. (This is only relevant if you build debs.)"

**Comment by IwanVosloo** [comment]
After fiddling with this a bit today we decided to update the apt archive indexes after each deb ha been built. This will result in it only being run if you actually need it, albeit perhaps multiple times if you have several packages. Removing the "post command action" stuff is a nice side effect.
