### ISSUE TITLE
When are the arguments for a guard evaluated? Any examples?

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#150]
I apologize: this query is probably better for the email list, but I cannot access it at work. 

First: is there any example available of using a guard within a transition to effect dynamic page flow?

Next: let's say that I wanted to route to a page based on whether and IntegerField was odd or even. If the relevant field were bound at compile-time instead of run-time, then the behavior would be based on the value of the field at the wrong time.

**Comment by metaperl** [comment]
I think I have come up with the perfect example for this. Let's say you do not want to reveal anything about the app until successful authentication. As a result, when the user visits the main URL, all they see is a login form.

If login is successful, then they transition to the app. And of course the app has the user email in the header. If login fails, then they are re-directed to the login screen.

**Comment by IwanVosloo** [comment]
Perhaps this example might help: https://www.reahl.org/pageflow/ 

Each guard is an Action. An Action wraps a callable. When the user clicks on a button, the following happens on the server:

1) any input given via Inputs in the Form is validated and set as attribute values on objects as specified by the relevant Fields.
2) the Action of the Event to which the Button is linked is called.
3) a decision is made which View to transition the user next, and as part of this the guard Action of each eligible Transition is evaluated.

This means that the values used at the time of evaluating the guard Action are always done at run time (because you call it), and at the time when it is called, all Form input has already been processed as received from the web browser.

**Comment by IwanVosloo** [comment]
Off the cuff.... to see only a login form when you visit the main page, your HTMLPage can have logic:

```
if user_logged_in:
   self.add_child(LoggedInPage(view))
else:
   self.add_child(LogInPage(view))
```
In this case, no redirection is necessary.

You can also use a ViewPrecondition to the home page which requires the user to be logged in, and then make it Detour to a login page. See: https://www.reahl.org/docs/4.0/web/fw.d.html#controlling-flow-via-detours-and-redirects
