### ISSUE TITLE
Rendering the home page of tutorial.login2bootstrap takes a long time

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#164]
When I click over to the register page and then return to the home page, the home page can take up to 20 seconds to render the simple text "Welcome email_address". 

I think every other page is being rendered each time we return to the home page? 

Is there some way to delay the generation of the `AccountUI` related pages? Or is this slowness related to something else?

**Comment by IwanVosloo** [comment]
I cannot reproduce that issue in Ubuntu in our vagrant box.

> I think every other page is being rendered each time we return to the home page?

No, what is created are just the ViewFactory instances. Only the single View you visit is created once you visit its URL.

The issue you get has to be caused by something else. 

I notice there is a switchover between http and https when you switch between / and /accounts/register in that example.  You can try to rule out possible network issues related to that by forcing everything to happen via http by setting the following in web.config.py:

```
web.default_http_port              	web.config.py	8000
web.default_http_scheme            	web.config.py	http
web.encrypted_http_port            	web.config.py	8000
web.encrypted_http_scheme          	web.config.py	http
```
or, force everything to https using:

```
web.default_http_port              	web.config.py	8363
web.default_http_scheme            	web.config.py	https
web.encrypted_http_port            	web.config.py	8363
web.encrypted_http_scheme          	web.config.py	https
```

**Comment by metaperl** [comment]
Switching it all to http eliminated the slowdown.
