### ISSUE TITLE
CSS Sampler? Title bar

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#186]
I realize that Reahl is using [Bootstrap](https://getbootstrap.com/) as its CSS framework. However, it would be nice to see how to style HTML elements with bootstrap classes.

My specific issue now can be stated in terms of the [access example](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/accessbootstrap/accessbootstrap.py) - the example currently shows the user login status on the left side...

If you take a look at the site we are on, Github, you will notice 
1. the user status is floated to the right.
2. the site name is floated to the left (it happens to be a logo, but it could be H1 text, which is what I want ... either that or this [display style](https://getbootstrap.com/docs/4.1/content/typography/#display-headings))
3. The title bar has inverse color to the rest of the site.

How would one patch the  [access example](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/accessbootstrap/accessbootstrap.py)  so that the title bar accomplished all 3 points mentioned above?

**Comment by metaperl** [comment]
I've gotten somewhat close. But do note that no tutorial shows an example of header or footer text floating left or right. Furthermore do note that most modern websites have quite a few columns of text in the footer. E.g., [Wordpress.org](https://wordpress.org/) has 6 columns across the bottom. and it also has two rows in the header, with some items being left-justified and right justified. 

For Reahl to swim with the big fish, it needs to be able to do this.

Here is my attempt:

```python

class MainPage(HTML5Page):
    def __init__(self, view, bookmarks):
        super(MainPage, self).__init__(view)
        self.use_layout(PageLayout(document_layout=Container()))
        contents_layout = ColumnLayout(
            ColumnOptions('left', ResponsiveSize(lg=2)),
            ColumnOptions('main', ResponsiveSize(lg=8)),
            ColumnOptions('right', ResponsiveSize(lg=2)),
        ).with_slots()
        self.layout.contents.use_layout(contents_layout)

        login_session = LoginSession.for_current_session()
        if login_session.is_logged_in():
            logged_in_as = login_session.account.email
            _bookmarks = bookmarks['authed']
        else:
            logged_in_as = 'Not logged in'
            _bookmarks = bookmarks['not_authed']


        self.layout.header.add_child(P(view, text=logged_in_as))
        self.layout.header.add_child(Nav(view).use_layout(TabLayout()).with_bookmarks(_bookmarks))
```

the bookmarks in the bookmarks dictionary only use the main slot. I just need to figure out how to get the Title in the left slot and the logout button in the the right slot.

**Comment by IwanVosloo** [comment]
I am going to give you a completely different answer to what you've done there.... but just for completeness: you can specify what goes into which slot when you define a view by using [set_slot](https://www.reahl.org/docs/4.0/web/fw.d.html?highlight=set_slot#reahl.web.fw.ViewFactory.set_slot)

**Comment by IwanVosloo** [comment]
A [PageLayout](https://www.reahl.org/docs/4.0/web/layout.d.html?highlight=pagelayout) already creates a header, content area and footer. So, ideally you should be adding proper header content to its `.header` and `.footer`.

The other thing to keep in mind is that we're trying to provide an abstraction of Bootstrap here, and the Bootstrap way of dealing with a header would be to add a [Navbar](https://www.reahl.org/docs/4.0/web/bootstrap/navbar.d.html?highlight=navbar#module-reahl.web.bootstrap.navbar).

I have to tell you trying to change what Bootstrap provides into a conceptual abstraction on the level where we want to work is not at all easy. We have cut some corners in the sense that we do not always allow the full flexibility that Bootstrap itself would allow you to do. The reason why we cut these corners is that when we hit an actual concrete use case we are always in a better position to debate/analyse the issue and come up with an abstract solution.

I am telling you this because floating the "logged in" to the right here is an example of what we do not cater for. The rest is more or less covered. I would suggest something like this:

```
class AddressAppPage(HTML5Page):
    def __init__(self, view, home_bookmark):
        super(AddressAppPage, self).__init__(view)
        self.use_layout(PageLayout(document_layout=Container()))
        contents_layout = ColumnLayout(ColumnOptions('main', ResponsiveSize(lg=6))).with_slots()
        self.layout.contents.use_layout(contents_layout)

        layout = ResponsiveLayout('md', colour_theme='dark', bg_scheme='primary')
        navbar = Navbar(view, css_id='my_nav').use_layout(layout)
        navbar.layout.set_brand_text('Site name')
        nav = navbar.layout.add(Nav(view).with_bookmarks([home_bookmark]))
        nav.append_class('mr-auto')
        self.layout.header.add_child(navbar)

        login_session = LoginSession.for_current_session()
        if login_session.is_logged_in():
            logged_in_as = login_session.account.email
        else:
            logged_in_as = 'Not logged in'

        navbar.layout.add(TextNode(view, logged_in_as))
```

Notice how I've moved the Nav into the Navbar as well - that's just par for the course when using a bootstap Navbar but not strictly speaking neccessary. However, having it there is handy for my trick to get the 'logged-in-as' text floated to the right.

Normally the TextNode would not be floated to the right in a Navbar. I had to break through the abstraction we try to provide here and (a) ensure that there is another element before that text (the nav in this case - but it could have been an empty TextNode too...); and (b) I had to add the bootstrap class `mr-auto` to that element so it pushes the text to the right.

**Comment by IwanVosloo** [comment]
Regarding the footer, you are talking about something like [titled sections](http://www.designinginterfaces.com/firstedition/index.php?page=Titled_Sections)

I do actually want to create a Widget for that.... but here's a rough in-line bit of code. It needs more work but it should get you started (to be appended to the code in the previous comment):

```
        titled_sections = Div(view).use_layout(ColumnLayout(ColumnOptions('one', ResponsiveSize(lg=2)),
                                                            ColumnOptions('two', ResponsiveSize(lg=2)),
                                                            ColumnOptions('three', ResponsiveSize(lg=2)),
                                                            ColumnOptions('four', ResponsiveSize(lg=2)),
                                                            ColumnOptions('five', ResponsiveSize(lg=2)),
                                                            ColumnOptions('six', ResponsiveSize(lg=2))
                                                            ))
        titled_sections.layout.columns['one'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        titled_sections.layout.columns['two'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        titled_sections.layout.columns['three'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        titled_sections.layout.columns['four'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        titled_sections.layout.columns['five'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        titled_sections.layout.columns['six'].add_child(Nav(view).with_bookmarks([home_bookmark, home_bookmark, home_bookmark]))
        self.layout.footer.add_child(titled_sections)

```
