### ISSUE TITLE
Automatic saving of changed objects

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#192]
if you look at the code for [either tutorial on parameterised views](https://www.reahl.org/docs/4.0/tutorial/parameterised.d.html#how-to-define-a-parameterised-view) you will note that the `update` event doesnt do anything with SQLAlchemy - apparently just having fields which validate and bind new values in the object is enough. In contrast, a newly created object which gets fields bound by its fields does require an explicit save.

Are the aspects of Reahl SQLAlchemy support which automate this behavior documented somewhere.

**Comment by IwanVosloo** [comment]
Correct, the bound Fields do all that work. What also happens is that the framework takes care of transaction handling. The event itself does not need to do anything except maybe play a role when the next transition is decided.

It actually has nothing to do with SQLAlchemy per sé. The transaction handling, does in the sense that it relates to the database. But the Fields not.

The documentation that relates to this issue is the [user interaction](https://www.reahl.org/docs/4.0/tutorial/inputwidgets.d.html) section (which is perhaps not the place to point this fact out).

We can mention it in the example you cite, to explain why the update does not need to do anything.

(Actually, we have gone through a learning curve with documentation - especially the tutorial. Our last update was to make the tutorial much less wordy and less explanatory.)
