### ISSUE TITLE
DateField defaults to `dayfirst=True` and has default date in example code

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#194]
# Default parser expects day first

The fuzzy parser for dates [defaults to the day being first](https://github.com/reahl/reahl/blob/master/reahl-component/reahl/component/modelinterface.py#L1292). This should be configurable in some way instead of being a fixed choice. We don't expect the day first in the USA.

# Magical default value in example code

When one fires up the [htmlinputs example](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/web/basichtmlinputs/basichtmlinputs.py) one is surprised that the date field has a default value of `6 Nov 2018` because nothing about setting up this app (via `develop; createdbuser; createdb; createdbtables; serve) creates such a value and the source code does not do it either.

**Comment by IwanVosloo** [comment]
> Default parser expects day first

Parsing the date should also be done based on locale. That is a tricky problem to get right though since it is not something supported by Babel. I think we'd have to make use of something like [dateparser](https://pypi.org/project/dateparser/) to do that reliably.

> Magical default value in example code

This is actually not in the example code, it is the behaviour of [babel.dates.format_date when passed None as the date](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-component/reahl/component/modelinterface.py#L1297). Perhaps an if is needed here to return an empty string instead of calling Babel.

**Comment by IwanVosloo** [comment]
It seems that using dateparser for this is not all that simple.... For example, it would seem that 'en-US' locale is not supported:

```
dateparser.parse('2017-11-10', locales=['en-US']
```

errors with:

```
ValueError: Unknown locale(s): 'en-US
```

Currently. Also, from [the docs](https://github.com/scrapinghub/dateparser/blob/28e6c721a11eba470f9cac98114e76b13d226291/README.rst#ootb-language-based-date-order-preference): 

> Ordering is not locale based

I am starting to think it is not worth the effort, and that we should rather change it to using a datepicker as per #233 ...
