### ISSUE TITLE
reahl.component.exceptions.ProgrammerError: Could not detect event. Did the browser submit the button? 

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#202]
Apparently related to https://github.com/reahl/reahl/issues/24 , I have a valid reason for two buttons on my form: if there are no search results, then only a "Cancel and return" button is needed. However if there are search results then an "Update and return" and a "cancel and return" button should be on the form showing the search results (which is always exactly 1 database record) and the related events and transitions should do as instructed. However with this code:

`btn2` behaves as programmed but clicking `btn` leads to

```
reahl.component.exceptions.ProgrammerError: Could not detect event. 
Did the browser submit the button? 
Inputs submitted: []
```

I definitely think my requirements spec is reasonable. Does Reahl allow two buttons to be on the same form?

Also please note that once I add role-authorization logic, then the "Update and Return" button's appearance will be further conditionalized on role.

**Comment by metaperl** [comment]
Also, when there is only one button on the form but the button is added via the `else` branch of an `if-else` statement, you get the same exception thrown:



The problem with this is an "Update and Return" button makes no sense when there are no search results. The following code provides a button that works whether or not there are search, but from a human perspective, it is disconcerting to have a button that says "Update and Return" when there is nothing to update:

**Comment by IwanVosloo** [comment]
> Does Reahl allow two buttons to be on the same form?

Yes....

I will have to see more of your code to try help you debug this one.

What does the bit look like that @exposed the events in question?

**Comment by IwanVosloo** [comment]
On second thought... it would be best if you can reproduce this in a repo I can fork and play with.

This: 

> ['account_number', 'check_number', 'date_issued', 'amount', 
> 'transaction_id', 'last_updated', 'event.update?'] Events detected: []

indicates that the button named "update" was submitted. I'd have to dig deeper in the stack to know why it was not seen as an event.

I'd want to see what happens when that request got to [ButtonInput.get_ocurred_event](https://github.com/reahl/reahl/blob/2f3aa40aef692531cc46e0acfd36e7005e6eaed4/reahl-web/reahl/web/ui.py#L1937) and, in the next call in [Event.occurred](https://github.com/reahl/reahl/blob/2f3aa40aef692531cc46e0acfd36e7005e6eaed4/reahl-component/reahl/component/modelinterface.py#L1023)

One possibility is that the Event is not writable (but then you should not have been able to click on it).

**Comment by metaperl** [comment]
Actually I have all that working. The only issue now is that the buttons are too together as this screenshot shows:

![buttons-too-close-together](https://user-images.githubusercontent.com/21293/48294226-37ccab00-e440-11e8-91de-31cd87685f54.PNG)

The code creating this is:

```python

class SearchCheckRigidResultsForm(Form):
    def __init__(self, view, row):
        super(__class__, self).__init__(view, 'add_form')

        LOGGER.warning("self.row={}".format(row))

        grouped_inputs = self.add_child(FieldSet(view, legend_text='Results of Search:'))
        grouped_inputs.use_layout(GridFormLayout(ResponsiveSize(lg=4), ResponsiveSize(lg=8)))

        # Cancel Button
        def cancel_button():
            if row is None:
                o = Check()
            else:
                o = row
            return grouped_inputs.add_child(Button(self, o.events.cancel))

        # Update Button
        def update_button():
            btn = grouped_inputs.add_child(Button(self, row.events.update))
            btn.use_layout(ButtonLayout(style='primary'))
            return btn

        if not row:
            # grouped_inputs.add_child(TextNode(view, 'No results'))
            grouped_inputs.add_child(P(view, text='No search results'))
            cancel_button()

        else:
            grouped_inputs.layout.add_input(TextInput(self, row.fields.account_number))
            grouped_inputs.layout.add_input(TextInput(self, row.fields.check_number))
            grouped_inputs.layout.add_input(TextInput(self, row.fields.date_issued))
            grouped_inputs.layout.add_input(TextInput(self, row.fields.date_cleared))

            grouped_inputs.layout.add_input(TextInput(self, row.fields.amount))
            grouped_inputs.layout.add_input(TextInput(self, row.fields.transaction_id))

            grouped_inputs.layout.add_input(TextInput(self, row.fields.last_updated))

            update_button()
            cancel_button()

```

**Comment by IwanVosloo** [comment]
As to your original question - I have answered that privately, but for posterity the issue was that you modified the database upon the GET so that a subsequent GET on that URL yielded completely different results - which would mean that a Button is no longer present on the page. 

As a general rule of thumb, you should not change anything in the database while rendering a page (ie, building Widgets).

**Comment by IwanVosloo** [comment]
Regarding the Buttons. Bootstrap wants you to group them together in a [button-group](https://getbootstrap.com/docs/4.0/components/button-group/).  We have not wrapped this yet, but you can do so by putting them in a Div with class 'btn-group'
