### ISSUE TITLE
Smooth the transition from tutorial.login2bootstrap to realistic registration code

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#208]
After one reads [tutorial.login2bootstrap](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html#re-using-the-user-interface-as-well) one is not clear on how to apply this tutorial to a real example in two ways:

1. How to configure an SMTP Server
2. What URLs are available in the pre-baked user interface.

# The current state of documentation on how to configure an SMTP server

The relevant config files and settings to configure a live production login system are not mentioned.

However, the dangerous setting warnings help:
```
WARNING:reahl.component.config:reahlsystem.debug in etc\reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:reahlsystem.root_egg in etc\reahl.config.py is using a dangerous default setting: login2bootstrap
WARNING:reahl.component.config:mail.smtp_port in etc\mailutil.config.py is using a dangerous default setting: 8025
WARNING:reahl.component.config:web.static_root in etc\web.config.py is using a dangerous default setting: c:\prg\login2bootstrap
WARNING:reahl.component.config:accounts.admin_email in etc\systemaccountmodel.config.py is using a dangerous default setting: admin@example.com
```

But these warnings are inaccurate because the files that it says the settings are coming from do not exist. But the inaccurate warnings are a godsend because I could not find any [docs on configuring smtp in reahl](https://www.reahl.org/docs/4.0/search.d.html?q=smtp&check_keywords=yes&area=default).

After some code search, I realized I need to create a `mailutil.config.py` file to configure the smtp server's port and host. But [there are no docs to this effect](https://www.reahl.org/docs/4.0/search.d.html?q=mailutil.config.py&check_keywords=yes&area=default) making it impossible for a developer to figure out how to do it without searching the code.

# A catalog of the URLs available for pre-baked user login and registration is needed

The tutorial example, when configured with a real SMTP server sends me an email with a code. But neither the email or the ui provide a way for me to enter this key and login. The [AccountUI docs](https://www.reahl.org/docs/4.0/domain/systemaccountui.d.html?highlight=accountui#reahl.domainui.bootstrap.accounts.AccountUI) mention a few more URLs but not the `/verify` one. 

This makes a person trying to transition from the tutorial to real code confused about how to get verified.

**Comment by craig-reahl** [comment]
### Answer: SMTP issue
The _config does not exist_ issue has been discussed [here](https://github.com/reahl/reahl/issues/145#issuecomment-431685110):

> It assumes default settings when the file is not there, or when the specific setting is not set in the file. So, to fix, you just need to create the config file and specify that setting.

I am aware that some software provides a config file with all default settings commented out. To keep our source code and examples lean, we do not do it.

Similarly, using `reahl listconfig` [as mentioned before](https://github.com/reahl/reahl/issues/141#issuecomment-431559407), 

`reahl listconfig -v -f etc`

one can see the files and settings needed. Perhaps we should add some more docs to [Component framework](https://www.reahl.org/af/docs/4.0/component/config.d.html)?

### Answer: A catalog of the URLs
Agreed, I think it requires some more documentation

**Comment by IwanVosloo** [comment]
> But these warnings are inaccurate because the files that it says the settings are coming from do not exist

We are dealing with this in #161 

>> A catalog of the URLs

>Agreed, I think it requires some more documentation

We have a number of TODO items for this:

As I understand it, we have omitted the /verify url from [AccountUI docs](https://www.reahl.org/docs/4.0/domain/systemaccountui.d.html?highlight=accountui#reahl.domainui.bootstrap.accounts.AccountUI). We'll have to add it.

I see that the[ tutorial.login2bootstrap example](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html#re-using-the-user-interface-as-well) can be improved as well, but part of the confusion has to do with the AccountUI itself:

In the tutorial, we should change the Nav to have a dropdown under register (or something) that include links to /registerHelp (the troubleshooting procedure) and also to /verify.

The bug is in AccountUI /registerHelp/pending (and on /congrats) where we direct the user to instructions in the email. By default there are no such instructions in the email, so I think they ought to be on these two pages, possibly with links to /verify.

We can improve the tutorial docs to run the user through a scenario that traverses verify successfully.
