### ISSUE TITLE
App class? Full URL (with port) to views?

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#226]
I wanted to configure the reset password emails as follows:

```python

from lib.appconfig import App

app = App()

accounts.admin_email = 'overseer@me.com'

accounts.new_password_subject   = f"Create a new password for $email in the {app.NAME} app."
accounts.new_password_email   = f""" 	You, or someone on your behalf requested to pick a new password for $email for the {app.NAME} app.

Your secret key is: $secret_key

Visit {app.choose_password_url} to complete the request.
"""

```

I had to create an app class myself which:
1. provided me the name of my app
1. provided urls (including the port) which could link the email reader to the appropriate view

Should something like this be a part of reahl and deriveable for refinement?

**Comment by IwanVosloo** [comment]
I think there is some documentation needed here. As you have noticed, those config settings are [python template strings](https://docs.python.org/3/library/string.html#template-strings).

I don't remember that we have documented this properly. We should document That they are templates and what identifiers one can use in them. (Currently its only $email and $secret_key.)

We can also add to those keys so you can refer to the URL and some sort of name identifying your app. I am not sure how tricky this will be..... On a first glance, I think the URL is very useful (and needed); the name of your app can easily be hardcoded in configuration though.

**Comment by metaperl** [comment]
> As you have noticed, those config settings are python template strings.

Yes. Now f-strings are maybe the most common way to do this.

> We can also add to those keys so you can refer to the URL and some sort of name identifying your app. I am not sure how tricky this will be.

I tried many different things and did not get a full domain name:

* `socket.getfqdn()`
* https://stackoverflow.com/questions/4271740/how-can-i-use-python-to-get-the-system-hostname
* https://www.reddit.com/r/aws/comments/a1ld9v/how_can_i_use_python_to_get_the_domain_name_of/

so I gave up and set an environmental variable with the domain name in it.

**Comment by IwanVosloo** [comment]
> Yes. Now f-strings are maybe the most common way to do this.

Yea, trouble is they are only in Python >= 3.6... so we can't use them yet.

We have actually spent quite a bit of time experimenting with the idea of passing URLs into those templates. It turns out to be very difficult for some kinds of info like your web app, or an URL computed by it.

At issue is the fact that the code that passes replacements to those templates live in a component that only deals with the underlying domain (`reahl-domain`). The UI is a separate thing that lives in `reahl-domainui`. Since `reahl-domainui` depends on `reahl-domain`, `reahl-domain` cannot contain any knowledge the other way around.

The only mechanism we have for dealing with letting A contribute info to B in the scenario where A depends on B is [dependency injection](https://www.reahl.org/docs/4.0/devmanual/dependencyinjection.d.html#id1). This mechanism however works at configuration time...but the relevant URL or app are only available later on, once the app has been `.assemble()`-ed. 

My explanation does not do the subtleties of the issue justice though...we tried a number of things... but after a day of trying stuff we have started to feel that the complexity it adds is not really worth it. Especially since there is a simple way to accomplish this: hard-code the URL in your configuration, or make a different plan - such as what you have done above.

I think your current solution is the right way to go about it. 

For interest's sake, this is how you'd get a "full url with port" from a view:

```
url = view.as_bookmark(user_interface).href
url_in_string = str(url)
```
