### ISSUE TITLE
tutorial.login2bootstrap refuses to operate entirely in https

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#240]
I configured `web.config.py` in [tutorial.login2bootstrap](https://github.com/reahl/reahl/tree/master/reahl-doc/reahl/doc/examples/tutorial/login2bootstrap) to serve entirely with https:

```python

from __future__ import print_function, unicode_literals, absolute_import, division
from login2bootstrap import LoginUI

web.site_root = LoginUI


web.default_http_port = 8008
web.default_http_scheme = 'https'
web.encrypted_http_scheme = 'https'
web.encrypted_http_port = 8008
```

and it fails to serve connections:

```
H:\>curl -vk http://localhost:8008
*   Trying 127.0.0.1...
* TCP_NODELAY set
*   Trying ::1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8008 failed: Connection refused
* connect to ::1 port 8008 failed: Connection refused
* Failed to connect to localhost port 8008: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8008: Connection refused
```

```
H:\>curl -vk https://localhost:8008
*   Trying 127.0.0.1...
* TCP_NODELAY set
*   Trying ::1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8008 failed: Connection refused
* connect to ::1 port 8008 failed: Connection refused
* Failed to connect to localhost port 8008: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8008: Connection refused
```

**Comment by craig-reahl** [comment]
You did not state how you are running your app, I will assume it is the **reahl development server**. When using the **reahl development server** to serve your app, you have to tell it which ports to use:

`reahl serve -p 8008 [config_dir]`

It will the listen on that port for all http traffic, and on 8371  (8008+363) for https traffic.
You would have to align your _web.config.py_ settings with this if you wan to use the **reahl development server**

See also:
`reahl serve -h`

**Comment by metaperl** [comment]
> It will the listen on that port for all http traffic, and on 8371 (8008+363) for https traffic.
You would have to align your web.config.py settings with this if you want to use the reahl development server

If that is the case then why did @IwanVosloo  set the port to 8363 for both http and https in [his comment here](https://github.com/reahl/reahl/issues/164#issuecomment-433697945)?

Next, if I'm using Apache in production via [WSGI](https://www.reahl.org/docs/4.0/web/fw.d.html?highlight=reahlwsgiapplication#reahl.web.fw.ReahlWSGIApplication) how should `web.config.py` set the following variables to ensure that all traffic for every URL goes through https:

* web.default_http_port 
* web.default_http_scheme 
* web.encrypted_http_scheme 
* web.encrypted_http_port 

Wouldnt it be a huge security risk to run a web application out in the cloud without encrypting the traffic of every URL visited?

**Comment by craig-reahl** [comment]
Sure, when **not** using the **reahl development server**, you should set the settings as @IwanVosloo suggests, however, you seem to have mixed up two things here. One, running your app using the reahl development server (i.e. `reahl serve`), versus running it through Apache and WSGI. The latter uses the settings @IwanVosloo  suggests.

**Comment by craig-reahl** [comment]
Perhaps @reahl/core should look at changing `reahl serve` to read the web.config and serve using the ports set there?

**Comment by IwanVosloo** [comment]
It all depends on how you start up the web server.

When using `reahl serve etc/` we serve http on 8000 and https on 8363 as you can see when starting the server up:

> Serving http on port 8000, https on port 8363 (config=etc/)

Whatever you do in web.config.py should be based on how you start the server up. My [previous instructions](https://github.com/reahl/reahl/issues/164#issuecomment-433697945) are based on these default settings. 

The point is to be on https only you have to make the http scheme 'https' and its port the same as the port on which your server serves https.

> I configured web.config.py in tutorial.login2bootstrap to serve entirely with https...

To diagnose your problem we need to know how you started the webserver? What ports does it report when starting up? 8008 does not seem like a likely https port. We also need to know the contents of web.config.py.

TO transplant this to AWS, you will need to know how apache is configured. It will have a port on which it serves http and another on which it serves https. To be https only, change the default_http_scheme to 'https' and the default_http_port to wherever your apache serves its https.

**Comment by metaperl** [comment]
> as you can see when starting the server up:

So in 4.0.5 and later the local server gives a report of the ports it serves on?

**Comment by metaperl** [comment]
> Perhaps @reahl/core should look at changing reahl serve to read the web.config and serve using the ports set there?

Yes, that would help for consistency --- you would use the same config for the WSGI wrapper and `reahl serve`.

**Comment by IwanVosloo** [comment]
>> as you can see when starting the server up:

> So in 4.0.5 and later the local server gives a report of the ports it serves on?

No, it has always given that report.

**Comment by IwanVosloo** [comment]
I think there are some misunderstandings here, and some things said in this issue are not correct...which makes reading it all a bit confusing to follow.

Can we please "reset" the conversation?

Here's my attempt:

### Lets start from scratch

This ticket states that "tutorial.login2bootstrap refuses to operate entirely in https".

I have written a bash script to test that theory and cannot reproduce the problem. Here it is: 

```
#!/bin/bash

reahl example -f tutorial.login2bootstrap
cd login2bootstrap
reahl setup develop -N
reahl createdb etc
reahl createdbtables etc

cat << EOF > etc/web.config.py
from login2bootstrap import LoginUI

web.site_root = LoginUI
web.default_http_scheme = 'https'
web.default_http_port = 8363
EOF

reahl serve etc&
sleep 5
curl -vk https://localhost:8363/

```
(please note the above leaves the server running and you'll have to kill it afterwards)

### What the above means

Reahl cares about whether a request comes in over http or https. It sometimes redirects you from one to the other to ensure things that are security sensitive (like passwords) really, really DO only traverse the net via https.

Reahl knows *nothing at all* about the webserver under which you are running it. You tell Reahl how you have set up your webserver by using the following config settings:

```
web.default_http_port      The http port used when an encrypted connection is not required
web.default_http_scheme    The http scheme used when an encrypted connection is not required

web.encrypted_http_port    The http port used for encrypted connections.
web.encrypted_http_scheme  The http scheme used for encrypted connections.

``` 

The first two of the above say "where, and using what protocol does the webserver serve 'normal' traffic".
The last two say "where does the webserver serve traffic that should definitely be encrypted in transit".

The above can be set to be the same protocol and port, but they don't have to be.

We know the default settings of the Reahl development server is to serve http on 8000 and https on 8363 (as it reports when it starts up).

The config above thus says:
- use as default scheme "https" (instead of http); and
- my server does that on port 8363 (instead of 8000)


*Do you understand this explanation?*

Because if you do I suggest we move to #239 which seems to be about doing this in the context of AWS.

**Comment by metaperl** [comment]
> I have written a bash script to test that theory and cannot reproduce the problem. Here it is:

I made the same changes to my `web.config.py` for the same example and was able to visit `http://localhost:8363/` and get back status 200

> The first two of the above say "where, and using what protocol does the webserver serve 'normal' traffic".
> The last two say "where does the webserver serve traffic that should definitely be encrypted in transit".

And how do we tell Reahl what is normal versus "should definitely be encrypted"? 
This breaks down into two scenarios: 
1. certain URLs are https 
1. all URLs are https. 

Let's take them one-by-one:

### If I want every URL visited via https only, how do I do that?

### If I want to selectively hint about https URLs other than login URLs, what do I do?

How do I changethis code:

        health = self.define_view('/health', title='Health Check')
        health.set_slot('main', LegalNotice.factory('Health check passed.', 'health'))

What is odd is that `set_as_security_sensitive` is a widget method but it is the view that defines the URL... it makes more sense for this to be a View or UrlBoundView method.

> Do you understand this explanation?

The explanation is crystal-clear. Furthermore, I have duplicated your results. I just want an answer about selective versus all-encompassing hinting about https URLs.

Of course, there is the lurking question about [this comment](https://github.com/reahl/reahl/issues/240#issuecomment-447621933):

> Perhaps @reahl/core should look at changing reahl serve to read the web.config and serve using the ports set there?

If reahl/core is not reading `web.config.py` to serve using those ports now, then how could the login2bootstrap example work for you and me when we set the port in `web.config.py`?

In fact, I changed the `web.default_http_port` to 8888 and curl did not find the web app:

```
H:\>curl -vk https://localhost:8888
*   Trying 127.0.0.1...
* TCP_NODELAY set
*   Trying ::1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8888 failed: Connection refused
* connect to ::1 port 8888 failed: Connection refused
* Failed to connect to localhost port 8888: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8888: Connection refused

H:\>
```

The final oddity is that http does not redirect to https when `web.default_http_scheme = 'https'`. For config file like this:

```
from login2bootstrap import LoginUI

web.site_root = LoginUI


web.default_http_scheme = 'https'
web.default_http_port = 8363
#web.encrypted_http_scheme = 'https'
#web.encrypted_http_port = 8008
```

curl returns this:

```
H:\>curl -vk http://localhost:8363
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8363 (#0)
> GET / HTTP/1.1
> Host: localhost:8363
> User-Agent: curl/7.63.0
> Accept: */*
>
* Recv failure: Connection was reset
* Closing connection 0
curl: (56) Recv failure: Connection was reset
```

**Comment by IwanVosloo** [comment]
> I made the same changes to my web.config.py for the same example and was able to visit http://localhost:8363/ and get back status 200

That does not look right. Did you mean to say you visited http**s**://localhost:8363/ ?

> If I want every URL visited via https only, how do I do that?

By setting the config as I posted, ie:

```
web.default_http_scheme = 'https'
web.default_http_port = 8363
```

> If I want to selectively hint about https URLs other than login URLs, what do I do?

For starters, then you have to have `web.default_http_scheme` (and port) point to an HTTP server, and the `web.encrypted_http_scheme` (and port) to an HTTPs server.

Reahl will then by default use the HTTP server except if it picks up that a certain view is "security sensitive". A view is deemed "security sensitive" if any widget displayed on it is security sensitive. A widget is security sensitive if one of the following is true:
- it has a [read_check](https://www.reahl.org/docs/4.0/web/fw.d.html?highlight=read_check#reahl.web.fw.Widget.read_check) set; or
- it has been [explicitly set as being security sensitive](https://www.reahl.org/docs/4.0/web/fw.d.html?highlight=read_check#reahl.web.fw.Widget.set_as_security_sensitive).

An Input derives its read_check from the Field it is bound to. So, for example, if you use a PasswordField (which is NOT readable ever), the associated Input will be security sensitive... and as a result the page will be served via HTTPs (or, more correctly, via `web.encrypted_http_scheme` (and port).

This is true even if the current user IS in fact able to read the particular Field: the fact that it has something governing whether people can read it (a `read_check`) means that not everyone should be able to read it and hence it has to be encrypted in transit.

> What is odd is that set_as_security_sensitive is a widget method but it is the view that defines the URL... it makes more sense for this to be a View or UrlBoundView method.

That perhaps feels odd, yes, but at the view level you don't typically have the detailed domain information about the details of each widget possibly on it...such as an Input linked to a password widget... to be able to make that decision. 

On the other hand, we've never really had a use case for making a view as a whole security sensitive. We could derive that from its own `read_check` too etc.

To be honest though, all of this is probably a bit overkill given that the world is pretty much moving to serving everything via https anyways...

> The explanation is crystal-clear. Furthermore, I have duplicated your results. I just want an answer about selective versus all-encompassing hinting about https URLs.

Great! Lets get to the rest then:

>Of course, there is the lurking question about this comment:
>
>>Perhaps @reahl/core should look at changing reahl serve to read the web.config and serve using the ports set there?
>
>If reahl/core is not reading web.config.py to serve using those ports now, then how could the login2bootstrap example work for you and me when we set the port in web.config.py?

It works because by default, `reahl serve` runs an HTTP server on 8000 and an HTTPS one on 8363. (..and because the config points it to those port/protocol combinations.)

As explained [in an earlier post](https://github.com/reahl/reahl/issues/240#issuecomment-447546639), you can change what ports the Reahl server uses by using commandline args. In that case, your config will have to match the changed ports.

> In fact, I changed the web.default_http_port to 8888 and curl did not find the web app:

If you want *that* config to work (with https scheme on 8888), you'l have to start the server in such a way that it runs on the ports you specify in the config:

`reahl serve -p 8525 etc`

Which will report:

`Serving http on port 8525, https on port 8888 (config=etc/)`

> The final oddity is that http does not redirect to https when web.default_http_scheme = 'https'. For config file like this:
```
web.default_http_scheme = 'https'
web.default_http_port = 8363
```
> curl returns this:
>  `H:\>curl -vk http://localhost:8363`
> ...
> `curl: (56) Recv failure: Connection was reset`

Yes, that makes sense because you are hitting an HTTPS server (on port 8363) using the HTTP protocol. It cannot understand what you are sending it because it cannot talk HTTP. 

This is not about redirecting one from http to https, rather it is for redirecting one from an HTTP URL on an HTTP server to an equivalent HTTPS URL on an HTTPS-able server.

If you want to see this last curl redirect, you need to hit: 
```
curl -vk https://localhost:8000
```
