### ISSUE TITLE
should reahl report some things using `print` and other things with `logging`

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#241]
When at the command-line. `reahl serve` outputs certain things via `logging` and other things via `print` - and both are visible.

I was using a shell with Emacs to perform `reahl serve` and none of the print statements, such as [the ports](https://github.com/reahl/reahl/issues/240#issuecomment-447729908), are visible in that shell.

Should reahl using both `print` and `logging`?

**Comment by IwanVosloo** [comment]
> Should reahl using both print and logging?

I think so, yes. We use print in the commandline tools to build the user interface of the commandline tool.

Logging is used for other info, which can come from anywhere in the code really.

> I was using a shell with Emacs to perform reahl serve and none of the print statements, such as the ports, are visible in that shell.

That's weird because I use emacs all the time and always see that output.

Can you try the following and let me know whether you see the output of 'one' before the sleep starts of after (for each of):

`python -c "import time; print('one'); time.sleep(2); print('two')"`

then

`python -c "import time; print('one\n'); time.sleep(2); print('two')"`

and lastly

`python -c "import time; import sys; print('one'); sys.stdout.flush(); time.sleep(2); print('two')"`

**Comment by metaperl** [comment]
![image](https://user-images.githubusercontent.com/21293/50451109-3e7b8880-08ef-11e9-831d-3cf39200beb9.png)

**Comment by IwanVosloo** [comment]
Ok thanks. That means that even though I cannot reproduce on my end, we may make things better by flushing when we start up the server.
