### ISSUE TITLE
Parsing SQLAlchemy URL chokes on `#` or `?` in URL

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#245]
`reahl.component.dbutils.DatabaseControl` attempts to parse a connection URL on [line 227](https://github.com/reahl/reahl/blob/master/reahl-component/reahl/component/dbutils.py#L227)

However, the call to `urllib_parse.urlparse(url)` barfs on URLs with `#` or `?` in URL. I have updated [the related Python bug](https://bugs.python.org/issue33342) with a link to [some code that demonstrates the problem](https://gist.github.com/metaperl/fc6f43bf6b9a9f874b8f27e29695e68c). 

Out of curiosity why is the database URL parsed instead of simply being passed to SQLAlchemy?

**Comment by metaperl** [comment]
If you use `urllib.parse.quote` and `unquote` on the password, then the `#` or `?` is escaped and does not lead to this problem. 

```python
# from six.moves.urllib import parse as urllib_parse
from urllib.parse import urlparse, quote

def parsefn(url):
    # return urllib_parse.urlparse(url)
    return urlparse(url)

def try_parse(url):
    uri_parts = parsefn(url)
    print(f"\tURI Parts={uri_parts}")
    if uri_parts.fragment:
        print("\t\t***FAILED PARSE - fragment should be empty***")
    if uri_parts.query != 'sslmode=required':
        print("\t\t***FAILED PARSE - actual query parm not parsed***")

def make_url(password):
    url = f'postgresql://kara_admin:{password}@hifi-kara-db-dev.do.aws/kara?sslmode=required'
    return url

passwords = """
bob
vLrnXUW1.DQ+3ya#=p}7gy{KS+3d
vLrnXUW1.DQ+3ya?=p}7gy{KS+3d
vLrnXUW1.DQ+3ya=p}7gy{KS+3d
""".split()

for password in passwords:
    print(f"------------------------\nPassword={password}")
    password = quote(password)
    url = make_url(password)
    try_parse(url)

```

**Comment by IwanVosloo** [comment]
> Out of curiosity why is the database URL parsed instead of simply being passed to SQLAlchemy?

Because we want to get all that info from the URL so that we can use it in various other ways, like when we do stuff using commandline tools.

We ALSO additionally pass the URL straight to sqlqlchemy.

It makes sense to me that, if you want a password in an URL that it would have to be quoted so it can conform to an URLs syntax. According to [rfc2396](https://tools.ietf.org/html/rfc2396.html) a pound sign is not one of the excluded ascii characters amongst others. From section 2.4.3:
> The character "#" is excluded  because it is used to delimit a URI from a fragment identifier in URI   references (Section 4)

So, I think the right thing to do is to always url quote the password as you state. I am guessing since you don't use our commandline tools (like reahl createdb) this is enough for your use case to work. (Correct me if I am wrong.)

BUT I am leaving this here as a bug, because the reahl commandline tools that use this info also would need to unquote what they get from the URL. And they currently don't do this.

Thanks

**Comment by metaperl** [comment]
> It makes sense to me that, if you want a password in an URL that it would have to be quoted so it can conform to an URLs syntax.

Proper URL escaping is not exclusive to the password aspect of the URL. As you can see, [SQLAlchemy unquotes both username and password from the URL connection string](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/url.py#L274).

> So, I think the right thing to do is to always url quote the password as you state.

The user would do this. The value of `reahlsystem.connection_uri` should already have **both** username and password quoted via the appropriate `urllib` call.

> the reahl commandline tools that use this info also would need to unquote what they get from the URL.

That should be handled in your `DatabaseControl` class before they ever get it I think.

But most importantly, once again we see the problems with trying to do things with command-line tools. If the string were simply passed to SQLAlchemy, then it would properly unquote url-encoded usernames and passwords. 

And everything you are doing with all these command-line tools can be done with SQLAlchemy - creating databases, dropping databases, etc. And that is how Flask and Django do it - they do it at ORM-level with Python code, not with command-line tools.

**Comment by IwanVosloo** [comment]
Yup, got that. For us to remember what to do:

> BUT I am leaving this here as a bug, because the reahl commandline tools that use this info also would need to unquote what they get from the URL. And they currently don't do this.
