### ISSUE TITLE
Does `reahl dropdbtables` need a --cascade argument?

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#247]
I just attempted to use `reahl dropdbtables` and it failed with the error:

```
         | psycopg2.InternalError: cannot drop table checkrecon_check because other objects depend on it
         | DETAIL:  view xxx_v1 depends on table checkrecon_check
         | HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

If there were a `--cascade` option then I could successfully drop the tables.

**Comment by IwanVosloo** [comment]
We can certainly add such an option.

**Comment by IwanVosloo** [comment]
We thought adding an option would be a simple matter of adding such an option and passing it through to SqlAlchemy. However, [Sqlalchemy's metadata.drop_all](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData.drop_all) does not have a cascade option either:

> method [sqlalchemy.schema.MetaData.](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData)drop_all(bind=None, tables=None, checkfirst=True)(https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData.drop_all)

[According to the authors of SqlAlchemy](https://groups.google.com/g/sqlalchemy/c/vTRGl364Aq4), adding a CASCADE here is not supported, since is not currently supported by all the backends used by SqlAlchemy.

Given the complications, its probably easier to just do a reahl dropdb instead.

If you do create extra database objects, like the view in the reported stacktrace, rather do it via SqlAlchemy and its Metadata - in which case it would be taken care of by sqlalchemy as is.
